name: Check & fix styling

on: [push, pull_request]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHP CS Fixer
        run: composer cs-fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: github.event_name == 'push'
        with:
          commit_message: Fix styling
  